### ISSUE TITLE
[Design] ONLINKERS Logo

### ISSUE THREAD

**Issue by cadrianxyz** [onlinkers/event-discovery-prototype#29]
# Organization Logo

### Design Purpose
> Long awaited, we need a logo.

### Design Requirements
- [ ] Exact Logo Specification (copyright purposes)
- [ ] Design

#### Additional Notes
https://medium.com/@whycaniuse/logo-specification-the-modern-process-b285a9cfaa9e
https://ori.hhs.gov/logo-specification-guide

**Comment by kraytaps** [comment]
have u taken a look at the logos i created on figma

**Comment by cadrianxyz** [comment]
I did!! Are they confirmed designs though? If we are going with them, I wrote this issue with having detailed logo specification sheets in mind.
