### ISSUE TITLE
***[LINT] Lint Change Requests During Development

### ISSUE THREAD

**Issue by kraytaps** [onlinkers/event-discovery-prototype#43]
**Annoying Lint Defaults To Change**

- [x] "no-unused-vars" (@kraytaps)
> Could we remove this check? It's really annoying and often times I need to just declare it and make sure it still runs but this forces us to actually use it on the page somewhere.

- [ ] "quotes: [1, "double"]
- [ ] "semi": [1, "always"]
- [ ] "indent": [1, 2] (@ad2969)
> Seems like we want a bit of consistency with string quotations, semi-colons, and indents - every commit seems to always be fixing these stylings at some point (particularly, @kraytaps' VSCode prettier plugin rules looks like it prefers certain things). We want commits to be as clean as possible so might as well implement these as strict eslint rules.

- [ ] "object-curly-spacing: [1, "always", { "arraysInObjects": true, "objectsInObjects": true }]" (@ad2969)
> Just want more consistency.

**Comment by kraytaps** [comment]
@ad2969 lemme know your opinion

**Comment by cadrianxyz** [comment]
@kraytaps Agree to turn "no-unused-vars" into 'warning'!!
Lets not close this issue and keep it just to log lints that anyone wants to change

**permission given to push to master for this LOL**

**Comment by cadrianxyz** [comment]
@kraytaps spacing, semi, and quotation rules requested. For semis, I personally prefer no semi-colons but this is always up for discussion.

**Comment by cadrianxyz** [comment]
Added another request for curly brace spacing.
