### ISSUE TITLE
[Rework] Redesign Event Details Page

### ISSUE THREAD

**Issue by kraytaps** [onlinkers/event-discovery-prototype#48]
# Event Details Page

### Purpose of Enhancement
* This page shouldn't consider light vs dark themes and change styles according to that -> keep it consistent regardless

#### What is required?
> Delete unnecessary components
- [ ] Wireframe
- [ ] HF design
- [ ] Working component

**Comment by cadrianxyz** [comment]
This might be quite urgent ya since its one of the **main** **_main_** components
