### ISSUE TITLE
[FR] User Sign Up and Sign In

### ISSUE THREAD

**Issue by kraytaps** [onlinkers/event-discovery-prototype#78]
# User Sign Up and Sign In

### Description of the feature
* make the sign in page actually work
* AWS Amplify? (Cognito and Auth)

### Purpose of the feature
* lets users sign up and sign in
* TODO: link things such as events the user liked, etc.

### Tasks to complete
- [ ] Integrate Amplify

**Comment by cadrianxyz** [comment]
Good stuff. This is related to [#12](https://github.com/onlinkers/event-discovery-api/issues/12)
AWS Cognito is pretty promising but still need to scope if it fits our needs best (with user permissions and the need to differentiate between 'hosts' and 'users' and such)
